services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: qr_menu
      POSTGRES_USER: qr_menu
      POSTGRES_PASSWORD: $$v%SGXVraH6
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://qr_menu:$$v%SGXVraH6@postgres:5432/qr_menu?schema=public
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      ADMIN_PATH: /admin
      SESSION_SECRET: hsWK6Pu4LB4xBHtCiSMfctFNZYYYdseNtMUgy6rrJDMjiP4x
      SEED_ADMIN_EMAIL: bilgisilem@lionelhotel.com.tr
      SEED_ADMIN_USERNAME: admin
      SEED_ADMIN_PASSWORD: "Lionel!1907."
      UPLOAD_DIR: /app/storage/uploads
      MAX_UPLOAD_MB: 4
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/storage/uploads

volumes:
  postgres_data:
  uploads:
